name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '8.0',
            '8.1'
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_${{ matrix.db-type }}
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: |
          composer --version
          composer install -o

      - name: PHPStan checks
        run: |
            composer stan-setup
            composer stan

      - name: CodeStyle checks
        run: composer cs-check

      - name: Codeception tests
        run: |
          if [[ ${{ matrix.php-version }} == '7.4' ]]; then
            vendor/bin/codecept run --coverage-xml
          else
            vendor/bin/codecept run
          fi

      - name: Code Coverage Report
        if: success() && matrix.php-version == '7.4'
        uses: codecov/codecov-action@v1

  prefer-lowest:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '8.0'
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql

      - name: Composer prefer-lowest
        run: composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable -o

      - name: Codeception tests
        run: vendor/bin/codecept run
